title: Yaxin's blog area
# author: GitHub User
email: yaxin.cheng@uwaterloo.ca
description: > # this means to ignore newlines until "show_exerpts:"
  Yaxin's blog area focuses on interesting ideas in tech fields, including solutions to programming problems, applications for tech gears.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Yaxin Cheng
  tagline: The developer you'd expect
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  YaxinCheng
    linkedIn: in/YaxinCheng
    #rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
